title: DataLink Hackathon
Description: > # your text below (remove <br> elements if you don't need line breaks)
  Credit Rating Prediction 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/ivan-perez-saez/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

